---
title: "R Notebook"
output: html_notebook
---

prereq:
install.packages("ggpolypath")


```{r}
library(readr)
library(ggpolypath)
library(ggplot2)
library(venn) 
```


```{r}
# read DEGs
setwd("/Users/iris/Downloads/Jan12/DEGs_filtered_updown_sorted_fc25")

DEG_day1_aEC_up <- read_csv("./DEG_day1_aEC_up_sorted.csv")
DEG_day1_aEC_down <- read_csv("./DEG_day1_aEC_down_sorted.csv")
DEG_day1_capEC_up <- read_csv("./DEG_day1_capEC_up_sorted.csv")
DEG_day1_capEC_down <- read_csv("./DEG_day1_capEC_down_sorted.csv")
DEG_day1_vEC_up <- read_csv("./DEG_day1_vEC_up_sorted.csv")
DEG_day1_vEC_down <- read_csv("./DEG_day1_vEC_down_sorted.csv")

DEG_day1_acapEC_up <- read_csv("./DEG_day1_acapEC_up_sorted.csv")
DEG_day1_acapEC_down <- read_csv("./DEG_day1_acapEC_down_sorted.csv")
DEG_day1_vcapEC_up <- read_csv("./DEG_day1_vcapEC_up_sorted.csv")
DEG_day1_vcapEC_down <- read_csv("./DEG_day1_vcapEC_down_sorted.csv")


DEG_day3_aEC_up <- read_csv("./DEG_day3_aEC_up_sorted.csv")
DEG_day3_aEC_down <- read_csv("./DEG_day3_aEC_down_sorted.csv")
DEG_day3_capEC_up <- read_csv("./DEG_day3_capEC_up_sorted.csv")
DEG_day3_capEC_down <- read_csv("./DEG_day3_capEC_down_sorted.csv")
DEG_day3_vEC_up <- read_csv("./DEG_day3_vEC_up_sorted.csv")
DEG_day3_vEC_down <- read_csv("./DEG_day3_vEC_down_sorted.csv")

DEG_day3_acapEC_up <- read_csv("./DEG_day3_acapEC_up_sorted.csv")
DEG_day3_acapEC_down <- read_csv("./DEG_day3_acapEC_down_sorted.csv")
DEG_day3_vcapEC_up <- read_csv("./DEG_day3_vcapEC_up_sorted.csv")
DEG_day3_vcapEC_down <- read_csv("./DEG_day3_vcapEC_down_sorted.csv")


DEG_day7_aEC_up <- read_csv("./DEG_day7_aEC_up_sorted.csv")
DEG_day7_aEC_down <- read_csv("./DEG_day7_aEC_down_sorted.csv")
DEG_day7_capEC_up <- read_csv("./DEG_day7_capEC_up_sorted.csv")
DEG_day7_capEC_down <- read_csv("./DEG_day7_capEC_down_sorted.csv")
DEG_day7_vEC_up <- read_csv("./DEG_day7_vEC_up_sorted.csv")
DEG_day7_vEC_down <- read_csv("./DEG_day7_vEC_down_sorted.csv")

DEG_day7_acapEC_up <- read_csv("./DEG_day7_acapEC_up_sorted.csv")
DEG_day7_acapEC_down <- read_csv("./DEG_day7_acapEC_down_sorted.csv")
DEG_day7_vcapEC_up <- read_csv("./DEG_day7_vcapEC_up_sorted.csv")
DEG_day7_vcapEC_down <- read_csv("./DEG_day7_vcapEC_down_sorted.csv")
```


```{r}
setwd("/Users/iris/Downloads/DEGs_filtered_updown_sorted")

DEG_day1_allEC_up <- read_csv("./DEG_day1_allEC_up_sorted.csv")
DEG_day1_allEC_down <- read_csv("./DEG_day1_allEC_down_sorted.csv")
DEG_day3_allEC_up <- read_csv("./DEG_day3_allEC_up_sorted.csv")
DEG_day3_allEC_down <- read_csv("./DEG_day3_allEC_down_sorted.csv")
DEG_day7_allEC_up <- read_csv("./DEG_day7_allEC_up_sorted.csv")
DEG_day7_allEC_down <- read_csv("./DEG_day7_allEC_down_sorted.csv")
```



```{r}
x <- list(
  aEC = unique(c(DEG_day1_aEC_up$gene, DEG_day3_aEC_up$gene, DEG_day7_aEC_up$gene), c(DEG_day1_aEC_up$gene, DEG_day3_aEC_up$gene, DEG_day7_aEC_up$gene)), 
  vEC = unique(c(DEG_day1_vEC_up$gene, DEG_day3_vEC_up$gene, DEG_day7_vEC_up$gene)),
  capEC = unique(c(DEG_day1_capEC_up$gene, DEG_day3_capEC_up$gene, DEG_day7_capEC_up$gene))
  )
```

```{r}
x <- list(
  aEC_1 = unique(c(DEG_day1_aEC_up$gene, DEG_day3_aEC_up$gene, DEG_day7_aEC_up$gene)), 
  vEC_1 = unique(c(DEG_day1_vEC_up$gene, DEG_day3_vEC_up$gene, DEG_day7_vEC_up$gene)),
  capEC_1 = unique(c(DEG_day1_capEC_up$gene, DEG_day3_capEC_up$gene, DEG_day7_capEC_up$gene)),
  aEC_3 = unique(c(DEG_day1_aEC_up$gene, DEG_day3_aEC_up$gene, DEG_day7_aEC_up$gene)), 
  vEC_3 = unique(c(DEG_day1_vEC_up$gene, DEG_day3_vEC_up$gene, DEG_day7_vEC_up$gene)),
  capEC_3 = unique(c(DEG_day1_capEC_up$gene, DEG_day3_capEC_up$gene, DEG_day7_capEC_up$gene)),
  aEC_7 = unique(c(DEG_day1_aEC_up$gene, DEG_day3_aEC_up$gene, DEG_day7_aEC_up$gene)), 
  vEC_7 = unique(c(DEG_day1_vEC_up$gene, DEG_day3_vEC_up$gene, DEG_day7_vEC_up$gene)),
  capEC_7 = unique(c(DEG_day1_capEC_up$gene, DEG_day3_capEC_up$gene, DEG_day7_capEC_up$gene))
  )
```



```{r}
library(readr)
ucla_degs <- read_csv("D:\\Shuting_Chen\\code\\sc-mTBI\\ucla.degs.csv", skip = 2)

pv <- 0.05
fc <- 0.25

ucla_degs <- ucla_degs[ucla_degs$`Cell Type` == "Endothelial",]
ucla_degs <- ucla_degs[ucla_degs$Log.fold.change > fc | ucla_degs$Log.fold.change < -fc,]
ucla_degs <- ucla_degs[ucla_degs$`P Value` < pv,]
ucla_degs <- ucla_degs[(ucla_degs$Log.fold.change > 0 & ucla_degs$PCT.TBI > 0.1) | (ucla_degs$Log.fold.change < 0 & ucla_degs$PCT.Sham > 0.1),]
```



# each day
```{r}
x <- list(
  aEC = unique(c(DEG_day1_aEC_up$gene), c(DEG_day1_aEC_down$gene)),
  vEC = unique(c(DEG_day1_vEC_up$gene),c(DEG_day1_aEC_down$gene)),
  capEC = unique(c(DEG_day1_capEC_up$gene),c(DEG_day1_capEC_down$gene))
  )
```

```{r}
x <- list(
  aEC = unique(c(DEG_day1_aEC_up$gene), c(DEG_day1_aEC_down$gene)),
  vEC = unique(c(DEG_day1_vEC_up$gene),c(DEG_day1_aEC_down$gene)),
  capEC = unique(c(DEG_day1_capEC_up$gene),c(DEG_day1_capEC_down$gene)),
  acapEC = unique(c(DEG_day1_acapEC_up$gene),c(DEG_day1_acapEC_down$gene)),
  vcapEC = unique(c(DEG_day1_vcapEC_up$gene),c(DEG_day1_vcapEC_down$gene))
  )
```

```{r}
pdf("/Users/iris/Downloads/venn/day1.pdf")
#venn(x, ilab=TRUE, box = FALSE, ggplot = TRUE, size = 0, lty = "blank", zcolor = c("#FFCC99", "#009999", "#CCFF66"), sncs = 1.1, ilcs = 0.9)
venn(x, ilab=TRUE, box = FALSE, ggplot = TRUE, size = 0, lty = "blank", zcolor = c("#f7cecc", "#9ccfe6", "#CCFF66", "#bdb5e1", "#f7b722"), sncs = 1.1, ilcs = 0.9)
dev.off()
```


```{r}
x <- list(
  aEC = unique(c(DEG_day1_aEC_up$gene), c(DEG_day1_aEC_down$gene)),
  vEC = unique(c(DEG_day1_vEC_up$gene),c(DEG_day1_aEC_down$gene)),
  capEC = unique(c(DEG_day1_capEC_up$gene),c(DEG_day1_capEC_down$gene)),
  UCLA = ucla_degs$Gene
  )
```

```{r}
pdf("day1+UCLA.pdf")
#venn(x, ilab=TRUE, box = FALSE, ggplot = TRUE, size = 0, lty = "blank", zcolor = c("#FFCC99", "#009999", "#CCFF66", "#CC99CC"), sncs = 1.1, ilcs = 0.9)
venn(x, ilab=TRUE, box = FALSE, ggplot = TRUE, size = 0, lty = "blank", zcolor = c("#f7cecc", "#9ccfe6", "#CCFF66", "#bdb5e1", "#f7b722"), sncs = 1.1, ilcs = 0.9)

dev.off()
```


```{r}
x <- list(
  aEC = unique(c(DEG_day3_aEC_up$gene), c(DEG_day3_aEC_down$gene)),
  vEC = unique(c(DEG_day3_vEC_up$gene),c(DEG_day3_aEC_down$gene)),
  capEC = unique(c(DEG_day3_capEC_up$gene),c(DEG_day3_capEC_down$gene)),
  acapEC = unique(c(DEG_day3_acapEC_up$gene),c(DEG_day3_acapEC_down$gene)),
  vcapEC = unique(c(DEG_day3_vcapEC_up$gene),c(DEG_day3_vcapEC_down$gene))
  )
```

```{r}
pdf("/Users/iris/Downloads/venn/day3.pdf")
#venn(x, ilab=TRUE, box = FALSE, ggplot = TRUE, size = 0, lty = "blank", zcolor = c("#FFCC99", "#009999", "#CCFF66"), sncs = 1.1, ilcs = 0.9)
venn(x, ilab=TRUE, box = FALSE, ggplot = TRUE, size = 0, lty = "blank", zcolor = c("#f7cecc", "#9ccfe6", "#CCFF66", "#bdb5e1", "#f7b722"), sncs = 1.1, ilcs = 0.9)
dev.off()
```

```{r}
x <- list(
  aEC = unique(c(DEG_day3_aEC_up$gene), c(DEG_day3_aEC_down$gene)),
  vEC = unique(c(DEG_day3_vEC_up$gene),c(DEG_day3_aEC_down$gene)),
  capEC = unique(c(DEG_day3_capEC_up$gene),c(DEG_day3_capEC_down$gene)),
  UCLA = ucla_degs$Gene
  )
```

```{r}
pdf("day3+UCLA.pdf")
venn(x, ilab=TRUE, box = FALSE, ggplot = TRUE, size = 0, lty = "blank", zcolor = c("#FFCC99", "#009999", "#CCFF66", "#CC99CC"), sncs = 1.1, ilcs = 0.9)
dev.off()
```



```{r}
x <- list(
  aEC = unique(c(DEG_day7_aEC_up$gene), c(DEG_day7_aEC_down$gene)),
  vEC = unique(c(DEG_day7_vEC_up$gene),c(DEG_day7_aEC_down$gene)),
  capEC = unique(c(DEG_day7_capEC_up$gene),c(DEG_day7_capEC_down$gene)),
  acapEC = unique(c(DEG_day7_acapEC_up$gene),c(DEG_day7_acapEC_down$gene)),
  vcapEC = unique(c(DEG_day7_vcapEC_up$gene),c(DEG_day7_vcapEC_down$gene))
  )
```


```{r}
pdf("/Users/iris/Downloads/venn/day7.pdf")
#venn(x, ilab=TRUE, box = FALSE, ggplot = TRUE, size = 0, lty = "blank", zcolor = c("#FFCC99", "#009999", "#CCFF66"), sncs = 1.1, ilcs = 0.9)
venn(x, ilab=TRUE, box = FALSE, ggplot = TRUE, size = 0, lty = "blank", zcolor = c("#f7cecc", "#9ccfe6", "#CCFF66", "#bdb5e1", "#f7b722"), sncs = 1.1, ilcs = 0.9)

dev.off()
```

```{r}
x <- list(
  aEC = unique(c(DEG_day7_aEC_up$gene), c(DEG_day7_aEC_down$gene)),
  vEC = unique(c(DEG_day7_vEC_up$gene),c(DEG_day7_aEC_down$gene)),
  capEC = unique(c(DEG_day7_capEC_up$gene),c(DEG_day7_capEC_down$gene)),
  UCLA = ucla_degs$Gene
  )
```


```{r}
pdf("day7+UCLA.pdf")
venn(x, ilab=TRUE, box = FALSE, ggplot = TRUE, size = 0, lty = "blank", zcolor = c("#FFCC99", "#009999", "#CCFF66", "#CC99CC"), sncs = 1.1, ilcs = 0.9)
dev.off()
```

# allEC

```{r}
#use all EC
x <- list(
  UP_US = unique(c(DEG_day1_allEC_up$gene, DEG_day3_allEC_up$gene, DEG_day7_allEC_up$gene)),
  DOWN_US = unique(c(DEG_day1_allEC_down$gene, DEG_day3_allEC_down$gene, DEG_day7_allEC_down$gene)),
  UP_UCLA = ucla_degs[ucla_degs$Log.fold.change > 0,]$Gene,
  DOWN_UCLA = ucla_degs[ucla_degs$Log.fold.change < 0,]$Gene
  )
```

```{r}
# allEC
x <- list(
  UCLA = ucla_degs$Gene,
  TBI_Day1 = unique(c(DEG_day1_allEC_up$gene, DEG_day1_allEC_down$gene)),
  TBI_Day3 = unique(c(DEG_day3_allEC_up$gene, DEG_day3_allEC_down$gene)),
  TBI_Day7 = unique(c(DEG_day7_allEC_up$gene, DEG_day7_allEC_down$gene))
  )
```

```{r}
# capEC
x <- list(
  UCLA = as.character(na.omit(unlist(x$UCLA))),
  TBI_Day1 = as.character(na.omit(unique(c(DEG_day1_capEC_up$gene, DEG_day1_capEC_down$gene)))),
  TBI_Day3 = as.character(na.omit(unique(c(DEG_day3_capEC_up$gene, DEG_day3_capEC_down$gene)))),
  TBI_Day7 = as.character(na.omit(unique(c(DEG_day7_capEC_up$gene, DEG_day7_capEC_down$gene))))
  )

```

```{r}
# capEC
x <- list(
  UCLA = ucla_degs$Gene,
  TBI_Day1 = unique(c(DEG_day1_capEC_up$gene, DEG_day1_capEC_down$gene))
  )

```

```{r}
pdf("mTBI_3days_with_UCLA_JAN17.pdf")
venn(x, ilab=TRUE, box = FALSE, ggplot = TRUE, size = 0, lty = "blank", zcolor = c("#CC99CC", "#f7cecc", "#9ccfe6", "#CCFF66"), sncs = 1.1, ilcs = 0.9)
dev.off()
```

```{r}
# Helper function to display Venn diagram
display_venn <- function(x, ...){
  library(VennDiagram)
  grid.newpage()
  venn_object <- venn.diagram(x, filename = NULL, ...)
  grid.draw(venn_object)
}
```

```{r}
pdf("mTBI_3days_with_UCLA_JAN17.pdf")

display_venn(
        x,
        # Circles
        lty = 'blank',
        fill = c("#CC99CC", "#f7cecc", "#9ccfe6", "#CCFF66"),
        # Numbers
        cex = .9,
        # Set names
        cat.cex = 1,
        cat.default.pos = "outer",
)
dev.off()
```

# pairwise day
```{r}
x <- list(
  aEC_d1 = unique(c(DEG_day1_aEC_up$gene), c(DEG_day1_aEC_down$gene)),
  vEC_d1 = unique(c(DEG_day1_vEC_up$gene),c(DEG_day1_aEC_down$gene)),
  capEC_d1 = unique(c(DEG_day1_capEC_up$gene),c(DEG_day1_capEC_down$gene)),
  aEC_d3 = unique(c(DEG_day3_aEC_up$gene), c(DEG_day3_aEC_down$gene)),
  vEC_d3 = unique(c(DEG_day3_vEC_up$gene),c(DEG_day3_aEC_down$gene)),
  capEC_d3 = unique(c(DEG_day3_capEC_up$gene),c(DEG_day3_capEC_down$gene))
  )
```

```{r}
x <- list(
  aEC_d3 = unique(c(DEG_day3_aEC_up$gene), c(DEG_day3_aEC_down$gene)),
  vEC_d3 = unique(c(DEG_day3_vEC_up$gene),c(DEG_day3_aEC_down$gene)),
  capEC_d3 = unique(c(DEG_day3_capEC_up$gene),c(DEG_day3_capEC_down$gene)),
  aEC_d7 = unique(c(DEG_day7_aEC_up$gene), c(DEG_day7_aEC_down$gene)),
  vEC_d7 = unique(c(DEG_day7_vEC_up$gene),c(DEG_day7_aEC_down$gene)),
  capEC_d7 = unique(c(DEG_day7_capEC_up$gene),c(DEG_day7_capEC_down$gene))
  )
```

```{r}
x <- list(
  aEC_d1 = unique(c(DEG_day1_aEC_up$gene), c(DEG_day1_aEC_down$gene)),
  vEC_d1 = unique(c(DEG_day1_vEC_up$gene),c(DEG_day1_aEC_down$gene)),
  capEC_d1 = unique(c(DEG_day1_capEC_up$gene),c(DEG_day1_capEC_down$gene)),
  aEC_d7 = unique(c(DEG_day7_aEC_up$gene), c(DEG_day7_aEC_down$gene)),
  vEC_d7 = unique(c(DEG_day7_vEC_up$gene),c(DEG_day7_aEC_down$gene)),
  capEC_d7 = unique(c(DEG_day7_capEC_up$gene),c(DEG_day7_capEC_down$gene))
  )
```


# report shared

```{r}

Reduce(intersect, list(unique(c(DEG_day1_allEC_up$gene, DEG_day1_allEC_down$gene)), unique(c(DEG_day3_allEC_up$gene, DEG_day3_allEC_down$gene)), unique(c(DEG_day7_allEC_up$gene, DEG_day7_allEC_down$gene))))

Reduce(intersect, list(unique(c(DEG_day1_allEC_up$gene, DEG_day1_allEC_down$gene)), unique(c(DEG_day3_allEC_up$gene, DEG_day3_allEC_down$gene)), unique(c(DEG_day7_allEC_up$gene, DEG_day7_allEC_down$gene)), ucla_degs$Gene))

Reduce(intersect, list(DEG_day1_allEC_up$gene, DEG_day3_allEC_up$gene, DEG_day7_allEC_up$gene))
Reduce(intersect, list(DEG_day1_allEC_down$gene, DEG_day3_allEC_down$gene, DEG_day7_allEC_down$gene))
```

```{r}
# shared by 3 days
degs_usc <- Reduce(intersect, list(unique(c(DEG_day1_capEC_up$gene, DEG_day1_capEC_down$gene)), unique(c(DEG_day3_capEC_up$gene, DEG_day3_capEC_down$gene)), unique(c(DEG_day7_capEC_up$gene, DEG_day7_capEC_down$gene))))

# shared by 3 days + ucla
degs_usc_ucla <- Reduce(intersect, list(unique(c(DEG_day1_capEC_up$gene, DEG_day1_capEC_down$gene)), unique(c(DEG_day3_capEC_up$gene, DEG_day3_capEC_down$gene)), unique(c(DEG_day7_capEC_up$gene, DEG_day7_capEC_down$gene)), ucla_degs$Gene))

# up OR down
Reduce(intersect, list(DEG_day1_allEC_up$gene, DEG_day3_allEC_up$gene, DEG_day7_allEC_up$gene))
Reduce(intersect, list(DEG_day1_allEC_down$gene, DEG_day3_allEC_down$gene, DEG_day7_allEC_down$gene))
```


```{r}
# Filter rows where the 'Cell_Type' column is in the list
deg_day1_cap <- rbind(DEG_day1_capEC_up, DEG_day1_capEC_down)
deg_day3_cap <- rbind(DEG_day3_capEC_up, DEG_day3_capEC_down)
deg_day7_cap <- rbind(DEG_day7_capEC_up, DEG_day7_capEC_down)
```


```{r}
# select columns
deg_day1_cap <- deg_day1_cap[, !(names(deg_day1_cap) %in% c("Cell_Type", "p_val","pct.1","pct.2"))]
names(deg_day1_cap)[names(deg_day1_cap) == "p_val_adj"] <- "p_val_adj_from_dpi1"
names(deg_day1_cap)[names(deg_day1_cap) == "avg_log2FC"] <- "log2FC_from_dpi1"

deg_day3_cap <- deg_day3_cap[, !(names(deg_day3_cap) %in% c("Cell_Type", "p_val","pct.1","pct.2"))]
names(deg_day3_cap)[names(deg_day3_cap) == "p_val_adj"] <- "p_val_adj_from_dpi3"
names(deg_day3_cap)[names(deg_day3_cap) == "avg_log2FC"] <- "log2FC_from_dpi3"

deg_day7_cap <- deg_day7_cap[, !(names(deg_day7_cap) %in% c("Cell_Type", "p_val","pct.1","pct.2"))]
names(deg_day7_cap)[names(deg_day7_cap) == "p_val_adj"] <- "p_val_adj_from_dpi7"
names(deg_day7_cap)[names(deg_day7_cap) == "avg_log2FC"] <- "log2FC_from_dpi7"

ucla_degs_narrowed <- ucla_degs[, (names(ucla_degs) %in% c("Gene", "P Value","Log.fold.change"))]
names(ucla_degs_narrowed)[names(ucla_degs_narrowed) == "Gene"] <- "gene"
names(ucla_degs_narrowed)[names(ucla_degs_narrowed) == "P Value"] <- "p_val_adj_from_ucla"
names(ucla_degs_narrowed)[names(ucla_degs_narrowed) == "Log.fold.change"] <- "log2FC_from_ucla"
```


```{r}
# generate new tables
shared_dpi1to7 <- Reduce(function(x, y) merge(x, y, by = "gene", all = TRUE), list(deg_day1_cap[deg_day1_cap$gene %in% degs_usc, ],deg_day3_cap[deg_day3_cap$gene %in% degs_usc, ], deg_day7_cap[deg_day7_cap$gene %in% degs_usc, ]))

# output
write.csv(shared_dpi1to7, "venn_intersection_dpi1&3&7.csv", quote = F, row.names = F)

# generate new tables
shared_dpi1to7_ucla <- Reduce(function(x, y) merge(x, y, by = "gene", all = TRUE), list(deg_day1_cap[deg_day1_cap$gene %in% degs_usc_ucla, ],deg_day3_cap[deg_day3_cap$gene %in% degs_usc_ucla, ], deg_day7_cap[deg_day7_cap$gene %in% degs_usc_ucla, ], ucla_degs_narrowed[ucla_degs_narrowed$gene %in% degs_usc_ucla, ]))

# output
write.csv(shared_dpi1to7_ucla, "venn_intersection_dpi1&3&7_UCLA.csv", quote = F, row.names = F)

```




